# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c31a14d502ed92be114c7d0bd0e6899dfb1a8bfd701cabde8e659739e92bfd239b9255cccfdcf5f10f0c11cfb534674fc3313c7064c230e761a1a8048e6c75db

test:
  secret_key_base: 007696767979ed4ee74ddc028a3d8d8ca85a0396ae0ec5adb18b13d63c994b3fa762f675196d8a8668d9fc21eea7bdd0bac4b7d3bc3cb01433644669458a93b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
